version: '3.8'

services:
  tracker_app:
    build: .
    container_name: tracker_app
    ports:
      - "5567:5567"
    environment:
      - POSTGRES_USER=simon
      - POSTGRES_PASSWORD=trackerNPH9
      - POSTGRES_DB=trackerdb
    depends_on:
      - db
    command: ["tracker_app", "no_model"]

  db:
    image: postgres:11
    container_name: postgres_db
    environment:
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: trackerNPH9
      POSTGRES_DB: trackerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
